### ISSUE TITLE
Reporte de Práctica.

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/practica-4y5-bjny-huerto#1]
[Informe P4y5 - S3ISOF.pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-bjny-huerto/files/8713214/Informe.P4y5.-.S3ISOF.pdf)

**Comment by Rosa218** [comment]
Calificación : 20/20

**Comment by josealfredo79** [comment]
En esta practica no se realiza una descripcion correcta...

**Comment by josealfredo79** [comment]
Se debe realizar la correccion...

**Comment by Yabin-2021** [comment]
Aquí dejo la corrección del reporte de práctica.
[Informe P4y5 - S3ISOF.pdf](https://github.com/SistemasTecTlaxiaco/practica-4y5-bjny-huerto/files/8943714/Informe.P4y5.-.S3ISOF.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
